### PR TITLE
added theme toggle for dark/light mode

### PR DESCRIPTION
**Pull request by cnowdev**
This PR Resolves issue #13

### CODE REVIEW

**Comment by cnowdev** [comment]
I've created a PR for this issue. Merge if possible

**Comment by Deepak91168** [comment]
It would be better if toggle btn size is not too large and cursor should change to pointer on hover, white btn would be better as it goes well with both light and dark mode.
Rest amazing work!

**Review by Deepak91168 — CHANGES_REQUESTED** [review]
It would be better if toggle btn size is not too large and cursor should change to pointer on hover, white btn would be better as it goes well with both light and dark mode.
Rest amazing work!

**Review by Deepak91168 — CHANGES_REQUESTED** [review]
In Bubble sort algo. timer is not stopping might be something changed in it :) please fix it

**Review by Deepak91168 — APPROVED** [review]

**Pull request closed without merging**
